source $CRYPTOBIGBRO_PATH_TO_CODE/venv/bin/activate
pushd $CRYPTOBIGBRO_PATH_TO_DATA
python $CRYPTOBIGBRO_PATH_TO_CODE/cbpro-account-history.py $CRYPTOBIGBRO_ACCOUNT_CONFIG -c $CRYPTOBIGBRO_ACCOUNT_CACHE -p $CRYPTOBIGBRO_ACCOUNT_PORT